# Generated by Django 4.1 on 2024-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_restaurant_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
