# Generated by Django 4.1 on 2024-02-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
    ]
