# Generated by Django 4.1 on 2024-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_event_genre_event_location_event_price_range_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
