# Generated by Django 4.1 on 2024-04-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_photo_image_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='未指定', max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='価格帯'),
        ),
    ]
