# Generated by Django 4.1 on 2024-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_restaurant_category_alter_restaurant_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='restaurant_photos'),
        ),
    ]
